version: '2'
services:
    pangu-app:
        image: pangu
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pangu-mysql:3306/pangu?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pangu-mysql:
        extends:
            file: mysql.yml
            service: pangu-mysql
